class Solution:
    def dna(seq):
        a = seq.count('A')
        g = seq.count('G')
        c = seq.count('C')
        t = seq.count('T')
        print("{} {} {} {}".format(a, c, g, t))
    
    if "__main__" == __name__:
        dna(
            "TCAGGCCGTAATAGGCCAACCCAGCGGAATGCTCATCGCGCGGAGCAACCAGTAAAGGACTGGTTGCGCACGGGTTATACGAATGCTAAGGTCTTACTTACATAAGAAAGCTGCCGAAATTCATAACGGTCTCTATTTCATCCACGGCGGCCCTACCATAGTTCGTAGTTCACCGGATCTCACTACAAGTGAAATTCGGTTGTGCCGTTATCTATCTTGCTCTGCTTCACTTCTTGTCTGTGAACGTGGGTTGTTTACAGCCTCACTACGCTTGGTGCGACGAACGTGTGGTGAGAATGCCCCCAGTCCTACCTTCGAAAGTTATAAATGAGACGGTGCTGACTGGAGTATTTGACGTCGCGCGCTCTTATTATCTGTCAGGACCACCTTTCTCTTCGCAGCCCGCTACGTTCCGTAAATGTCTATGTGAGCACAGTCCAGCCGGTTAACGTCATTTTCGCAACCTACTACTTGGCCGAAGCCCACAGTCCACACTGTTGGGACAGCCAACCTTCTCGCATATTGCATCTCCCTCCTTGATCAATGCGGTACACGGACTCGATATTCTATGCGGAAAGGGGATGAGAATCTCGCACCAAGCTGGTCGAACCATCCTTCGCCATCTCGTTATTGAACGGGTGTAATTAGGCCCACCAGTTTGAAGCCATTACCGTTCTCGTGTGCATAGACCATCGCTGGTATCAAAGTCCCAGGGTTAGGGCTTAGGTCTAATGTGAACTAAGCCGTTGTAACTGCGTGTGCGCTATATTATATGCAGATTTCGCGACCGAATTAGCAGCGTCTATTTATATTTAAGGAGCGGTGAGGAAAAATCCCCTTGACCGCGACCCGGCGCGGAGACTAATCGCTGCAGTCAA"
        )