class Solution:
    def revc(s):
        rev_s = s[::-1]
        s_c = ""
        for c in rev_s:
            if c == 'A':
                s_c += 'T'
            elif c == 'T':
                s_c += 'A'
            elif c == 'G':
                s_c += 'C'
            else:
                s_c += 'G'
        print(s_c)
    
    if "__main__" == __name__:
        revc(
            "CATCAGGCCGTCCCGGATACACGGAACGGCTGTCCTTCGGAAGAGATAGTACTCTGGACGATCGTGTTTGTACTTTCTTTCCCCTATTGAAAGACTAGTCGCCCGTCATATCATCGGAGAATACTGACTTGTTTCTCCCAGGTTGAAAGGGCCTAAAGCCTCGCGGTTTTGGATTGCCTGCAGGCTTATGGCTTTCGACACGCGGGATCGGTACTCGCCGTTGTAACCCTTTAGGTTGGAATCGCGACAGATCTGATTCTTTGCGATTGCTGTAATATATCATATTCTAGTACAAATGCGGGACTTATCGTTTGTGGTTGTACAAACAACCAATGGAAGTTCTTACAAACACATGTCTAAGAACTGGCTGCCGTGCCTTGACAAAACTCTGAAGTTGGCATCTGGTATAGAAAACTTGTTTCCCCAAGACGTTTCTGACTTGTGCCATCCCCGATGACAGTCCGCAACCGGGGCTGTCACGTATTGGGTTGGTTCACAAATGGGCGAATGTGACTATGTTATGTACTTCTTCGCATTGAAGTTATCTTACGCTAGGCAGCAGGAATGTTAATGTCGCGGAGATACTCTATAGGCTACCGTAACCCATCCCTTACCATTGCGGAGGCGGCGGGGTCCGCCTCTGGTTATAACACTTCCGACGGCTTTCGTATTTAAGGCCATCATTACTTGTAATCACGAGTTCTCCCACCATCGAAGTGATCGCAGGAGTGTGCGACGGTTACATGTAGCGGAAGAAGGGATATGGCCGACAAAGGGCTGATCGTAATTGCGTCCTTGACCCCGAAAAGGCAACGGGCCCGAC"
        )